esphome:
  name: esphome-tester
  friendly_name: ESPHome Tester
  min_version: 2025.11.0
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: jerkstore
  password: REDACTED
  min_auth_mode: WPA2

light:
  - platform: rgb
    name: "ESPHome Dev LED"
    red: output_red
    green: output_green
    blue: output_blue
    gamma_correct: 2.2
    default_transition_length: 300ms

output:
  - platform: esp8266_pwm
    id: output_red
    pin: D1
    frequency: 1000 Hz
    inverted: true   # set to true if using common-anode LED
  - platform: esp8266_pwm
    id: output_green
    pin: D2
    frequency: 1000 Hz
    inverted: true
  - platform: esp8266_pwm
    id: output_blue
    pin: D3
    frequency: 1000 Hz
    inverted: true
